# Generated by Django 3.2.15 on 2022-09-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached', models.FileField(upload_to='uploads/', verbose_name='image')),
                ('postdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
