# Generated by Django 3.2.15 on 2022-10-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makefontapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='attached',
            field=models.FileField(upload_to='uploads/userwords/', verbose_name='image'),
        ),
    ]
